// This file is generated by scripts/generate-gallery-manifest.mjs.
// Do not edit manually; add/remove image folders under public/assets/gallery and rerun the generator.
import type { GalleryAlbum } from "./gallery";

export const galleryAlbums: GalleryAlbum[] = [
  {
    "id": "previous-events-appreciation",
    "title": "Appreciation",
    "images": [
      {
        "alt": "BTA GlobalX Appreciation photo",
        "height": 3572,
        "width": 5369,
        "id": "previous-events-appreciation-bta-global-1083-jpg",
        "title": "BTA Global-1083",
        "src": "/assets/gallery/previous-events/Appreciation/BTA%20Global-1083.jpg"
      },
      {
        "alt": "BTA GlobalX Appreciation photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-appreciation-bta-global-1086-jpg",
        "title": "BTA Global-1086",
        "src": "/assets/gallery/previous-events/Appreciation/BTA%20Global-1086.jpg"
      },
      {
        "alt": "BTA GlobalX Appreciation photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-appreciation-bta-global-1095-jpg",
        "title": "BTA Global-1095",
        "src": "/assets/gallery/previous-events/Appreciation/BTA%20Global-1095.jpg"
      },
      {
        "alt": "BTA GlobalX Appreciation photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-appreciation-bta-global-1098-jpg",
        "title": "BTA Global-1098",
        "src": "/assets/gallery/previous-events/Appreciation/BTA%20Global-1098.jpg"
      }
    ]
  },
  {
    "id": "previous-events-awardees",
    "title": "Awardees",
    "images": [
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3816,
        "width": 5736,
        "id": "previous-events-awardees-bta-global-1110-jpg",
        "title": "BTA Global-1110",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1110.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3816,
        "width": 5736,
        "id": "previous-events-awardees-bta-global-1113-jpg",
        "title": "BTA Global-1113",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1113.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-awardees-bta-global-1119-jpg",
        "title": "BTA Global-1119",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1119.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1123-jpg",
        "title": "BTA Global-1123",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1123.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1125-jpg",
        "title": "BTA Global-1125",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1125.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1127-jpg",
        "title": "BTA Global-1127",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1127.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3490,
        "width": 5245,
        "id": "previous-events-awardees-bta-global-1128-jpg",
        "title": "BTA Global-1128",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1128.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1131-jpg",
        "title": "BTA Global-1131",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1131.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1132-jpg",
        "title": "BTA Global-1132",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1132.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3635,
        "width": 5463,
        "id": "previous-events-awardees-bta-global-1134-jpg",
        "title": "BTA Global-1134",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1134.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1137-jpg",
        "title": "BTA Global-1137",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1137.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3677,
        "width": 5526,
        "id": "previous-events-awardees-bta-global-1154-copy-jpg",
        "title": "BTA Global-1154 - Copy",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1154%20-%20Copy.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3116,
        "width": 4684,
        "id": "previous-events-awardees-bta-global-1157-jpg",
        "title": "BTA Global-1157",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1157.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3453,
        "width": 5190,
        "id": "previous-events-awardees-bta-global-1161-jpg",
        "title": "BTA Global-1161",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1161.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3437,
        "width": 5165,
        "id": "previous-events-awardees-bta-global-1163-jpg",
        "title": "BTA Global-1163",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1163.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3437,
        "width": 5165,
        "id": "previous-events-awardees-bta-global-1166-jpg",
        "title": "BTA Global-1166",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1166.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3788,
        "width": 5693,
        "id": "previous-events-awardees-bta-global-1169-jpg",
        "title": "BTA Global-1169",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1169.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3437,
        "width": 5165,
        "id": "previous-events-awardees-bta-global-1171-jpg",
        "title": "BTA Global-1171",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1171.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3437,
        "width": 5165,
        "id": "previous-events-awardees-bta-global-1173-jpg",
        "title": "BTA Global-1173",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1173.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3890,
        "width": 5847,
        "id": "previous-events-awardees-bta-global-1180-jpg",
        "title": "BTA Global-1180",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1180.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3573,
        "width": 5370,
        "id": "previous-events-awardees-bta-global-1187-jpg",
        "title": "BTA Global-1187",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1187.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3849,
        "width": 5785,
        "id": "previous-events-awardees-bta-global-1189-jpg",
        "title": "BTA Global-1189",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1189.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3427,
        "width": 5150,
        "id": "previous-events-awardees-bta-global-1192-jpg",
        "title": "BTA Global-1192",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1192.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3837,
        "width": 5767,
        "id": "previous-events-awardees-bta-global-1198-jpg",
        "title": "BTA Global-1198",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1198.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3427,
        "width": 5150,
        "id": "previous-events-awardees-bta-global-1203-jpg",
        "title": "BTA Global-1203",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1203.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3927,
        "width": 5902,
        "id": "previous-events-awardees-bta-global-1209-jpg",
        "title": "BTA Global-1209",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1209.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3934,
        "width": 5912,
        "id": "previous-events-awardees-bta-global-1218-jpg",
        "title": "BTA Global-1218",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1218.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3844,
        "width": 5777,
        "id": "previous-events-awardees-bta-global-1221-jpg",
        "title": "BTA Global-1221",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1221.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3848,
        "width": 5784,
        "id": "previous-events-awardees-bta-global-1226-jpg",
        "title": "BTA Global-1226",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1226.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3847,
        "width": 5782,
        "id": "previous-events-awardees-bta-global-1230-jpg",
        "title": "BTA Global-1230",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1230.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3893,
        "width": 5851,
        "id": "previous-events-awardees-bta-global-1234-jpg",
        "title": "BTA Global-1234",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1234.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3858,
        "width": 5799,
        "id": "previous-events-awardees-bta-global-1240-jpg",
        "title": "BTA Global-1240",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1240.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3918,
        "width": 5888,
        "id": "previous-events-awardees-bta-global-1251-jpg",
        "title": "BTA Global-1251",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1251.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3826,
        "width": 5751,
        "id": "previous-events-awardees-bta-global-1256-jpg",
        "title": "BTA Global-1256",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1256.jpg"
      },
      {
        "alt": "BTA GlobalX Awardees photo",
        "height": 3689,
        "width": 5544,
        "id": "previous-events-awardees-bta-global-1258-jpg",
        "title": "BTA Global-1258",
        "src": "/assets/gallery/previous-events/Awardees/BTA%20Global-1258.jpg"
      }
    ]
  },
  {
    "id": "previous-events-bazaar-fair-highlights",
    "title": "Bazaar & Wellness Fair",
    "images": [
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-bazaar-fair-highlights-bta-global-33-jpg",
        "title": "BTA Global-33",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-33.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-bazaar-fair-highlights-bta-global-59-jpg",
        "title": "BTA Global-59",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-59.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 2670,
        "width": 4008,
        "id": "previous-events-bazaar-fair-highlights-bta-global-61-jpg",
        "title": "BTA Global-61",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-61.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-bazaar-fair-highlights-bta-global-129-jpg",
        "title": "BTA Global-129",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-129.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 2643,
        "width": 3968,
        "id": "previous-events-bazaar-fair-highlights-bta-global-146-jpg",
        "title": "BTA Global-146",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-146.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 2831,
        "width": 4250,
        "id": "previous-events-bazaar-fair-highlights-bta-global-170-jpg",
        "title": "BTA Global-170",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-170.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-bazaar-fair-highlights-bta-global-176-jpg",
        "title": "BTA Global-176",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-176.jpg"
      },
      {
        "alt": "BTA GlobalX Bazaar & Wellness Fair photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-bazaar-fair-highlights-bta-global-197-jpg",
        "title": "BTA Global-197",
        "src": "/assets/gallery/previous-events/Bazaar%20%26%20%20Fair%20highlights/BTA%20Global-197.jpg"
      }
    ]
  },
  {
    "id": "previous-events-kwc-grand-finale-2025",
    "title": "KWC Grand Finale 2025",
    "images": [
      {
        "alt": "BTA GlobalX KWC Grand Finale 2025 photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-kwc-grand-finale-2025-bta-global-746-jpg",
        "title": "BTA Global-746",
        "src": "/assets/gallery/previous-events/KWC%20Grand%20Finale%202025/BTA%20Global-746.jpg"
      },
      {
        "alt": "BTA GlobalX KWC Grand Finale 2025 photo",
        "height": 3253,
        "width": 4889,
        "id": "previous-events-kwc-grand-finale-2025-bta-global-780-jpg",
        "title": "BTA Global-780",
        "src": "/assets/gallery/previous-events/KWC%20Grand%20Finale%202025/BTA%20Global-780.jpg"
      },
      {
        "alt": "BTA GlobalX KWC Grand Finale 2025 photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-kwc-grand-finale-2025-bta-global-786-jpg",
        "title": "BTA Global-786",
        "src": "/assets/gallery/previous-events/KWC%20Grand%20Finale%202025/BTA%20Global-786.jpg"
      },
      {
        "alt": "BTA GlobalX KWC Grand Finale 2025 photo",
        "height": 3315,
        "width": 4982,
        "id": "previous-events-kwc-grand-finale-2025-bta-global-801-jpg",
        "title": "BTA Global-801",
        "src": "/assets/gallery/previous-events/KWC%20Grand%20Finale%202025/BTA%20Global-801.jpg"
      },
      {
        "alt": "BTA GlobalX KWC Grand Finale 2025 photo",
        "height": 3701,
        "width": 5562,
        "id": "previous-events-kwc-grand-finale-2025-bta-global-812-jpg",
        "title": "BTA Global-812",
        "src": "/assets/gallery/previous-events/KWC%20Grand%20Finale%202025/BTA%20Global-812.jpg"
      },
      {
        "alt": "BTA GlobalX KWC Grand Finale 2025 photo",
        "height": 3006,
        "width": 4518,
        "id": "previous-events-kwc-grand-finale-2025-bta-global-821-jpg",
        "title": "BTA Global-821",
        "src": "/assets/gallery/previous-events/KWC%20Grand%20Finale%202025/BTA%20Global-821.jpg"
      }
    ]
  },
  {
    "id": "previous-events-our-2nd-year-anniversary-celebration",
    "title": "Our Second Year Anniversary Celebration",
    "images": [
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 4336,
        "width": 2888,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-2-jpg",
        "title": "BTA Global-2",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-2.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 3013,
        "width": 4523,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-4-jpg",
        "title": "BTA Global-4",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-4.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 2475,
        "width": 3716,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-5-jpg",
        "title": "BTA Global-5",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-5.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 3373,
        "width": 2247,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-7-jpg",
        "title": "BTA Global-7",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-7.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 2952,
        "width": 4432,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-10-jpg",
        "title": "BTA Global-10",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-10.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-17-jpg",
        "title": "BTA Global-17",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-17.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 2576,
        "width": 3868,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-35-jpg",
        "title": "BTA Global-35",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-35.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 4528,
        "width": 3016,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-41-jpg",
        "title": "BTA Global-41",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-41.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 2721,
        "width": 4085,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-73-jpg",
        "title": "BTA Global-73",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-73.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 2699,
        "width": 4052,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-74-jpg",
        "title": "BTA Global-74",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-74.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-77-jpg",
        "title": "BTA Global-77",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-77.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 4463,
        "width": 2973,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-118-jpg",
        "title": "BTA Global-118",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-118.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-119-jpg",
        "title": "BTA Global-119",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-119.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 3745,
        "width": 5629,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-595-jpg",
        "title": "BTA Global-595",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-595.jpg"
      },
      {
        "alt": "BTA GlobalX Our Second Year Anniversary Celebration photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-our-2nd-year-anniversary-celebration-bta-global-746-jpg",
        "title": "BTA Global-746",
        "src": "/assets/gallery/previous-events/Our%202nd%20Year%20Anniversary%20Celebration/BTA%20Global-746.jpg"
      }
    ]
  },
  {
    "id": "previous-events-red-carpet-interviews",
    "title": "Red Carpet Interviews",
    "images": [
      {
        "alt": "BTA GlobalX Red Carpet Interviews photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-red-carpet-interviews-bta-global-1280-jpg",
        "title": "BTA Global-1280",
        "src": "/assets/gallery/previous-events/Red%20Carpet%20Interviews/BTA%20Global-1280.jpg"
      },
      {
        "alt": "BTA GlobalX Red Carpet Interviews photo",
        "height": 3649,
        "width": 5484,
        "id": "previous-events-red-carpet-interviews-bta-global-1281-jpg",
        "title": "BTA Global-1281",
        "src": "/assets/gallery/previous-events/Red%20Carpet%20Interviews/BTA%20Global-1281.jpg"
      },
      {
        "alt": "BTA GlobalX Red Carpet Interviews photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-red-carpet-interviews-bta-global-1286-jpg",
        "title": "BTA Global-1286",
        "src": "/assets/gallery/previous-events/Red%20Carpet%20Interviews/BTA%20Global-1286.jpg"
      },
      {
        "alt": "BTA GlobalX Red Carpet Interviews photo",
        "height": 3959,
        "width": 5950,
        "id": "previous-events-red-carpet-interviews-bta-global-1288-jpg",
        "title": "BTA Global-1288",
        "src": "/assets/gallery/previous-events/Red%20Carpet%20Interviews/BTA%20Global-1288.jpg"
      },
      {
        "alt": "BTA GlobalX Red Carpet Interviews photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-red-carpet-interviews-bta-global-1299-jpg",
        "title": "BTA Global-1299",
        "src": "/assets/gallery/previous-events/Red%20Carpet%20Interviews/BTA%20Global-1299.jpg"
      },
      {
        "alt": "BTA GlobalX Red Carpet Interviews photo",
        "height": 3818,
        "width": 5739,
        "id": "previous-events-red-carpet-interviews-bta-global-1319-jpg",
        "title": "BTA Global-1319",
        "src": "/assets/gallery/previous-events/Red%20Carpet%20Interviews/BTA%20Global-1319.jpg"
      }
    ]
  },
  {
    "id": "previous-events-seminar-panel-discussion",
    "title": "Seminar & Panel Discussion",
    "images": [
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 3653,
        "width": 5491,
        "id": "previous-events-seminar-panel-discussion-bta-global-399-jpg",
        "title": "BTA Global-399",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-399.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 2508,
        "width": 3762,
        "id": "previous-events-seminar-panel-discussion-bta-global-406-jpg",
        "title": "BTA Global-406",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-406.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 2624,
        "width": 3936,
        "id": "previous-events-seminar-panel-discussion-bta-global-408-jpg",
        "title": "BTA Global-408",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-408.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 2624,
        "width": 3936,
        "id": "previous-events-seminar-panel-discussion-bta-global-409-jpg",
        "title": "BTA Global-409",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-409.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 2521,
        "width": 3782,
        "id": "previous-events-seminar-panel-discussion-bta-global-413-jpg",
        "title": "BTA Global-413",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-413.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 2624,
        "width": 3936,
        "id": "previous-events-seminar-panel-discussion-bta-global-417-jpg",
        "title": "BTA Global-417",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-417.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 2624,
        "width": 3936,
        "id": "previous-events-seminar-panel-discussion-bta-global-421-jpg",
        "title": "BTA Global-421",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-421.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-seminar-panel-discussion-bta-global-683-jpg",
        "title": "BTA Global-683",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-683.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-seminar-panel-discussion-bta-global-717-jpg",
        "title": "BTA Global-717",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-717.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-seminar-panel-discussion-bta-global-722-jpg",
        "title": "BTA Global-722",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-722.jpg"
      },
      {
        "alt": "BTA GlobalX Seminar & Panel Discussion photo",
        "height": 3785,
        "width": 5689,
        "id": "previous-events-seminar-panel-discussion-bta-global-727-jpg",
        "title": "BTA Global-727",
        "src": "/assets/gallery/previous-events/Seminar%20%26%20Panel%20Discussion/BTA%20Global-727.jpg"
      }
    ]
  },
  {
    "id": "previous-events-speakers",
    "title": "Speakers",
    "images": [
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-speakers-bta-global-907-jpg",
        "title": "BTA Global-907",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-907.jpg"
      },
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 3281,
        "width": 4931,
        "id": "previous-events-speakers-bta-global-929-jpg",
        "title": "BTA Global-929",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-929.jpg"
      },
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-speakers-bta-global-934-jpg",
        "title": "BTA Global-934",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-934.jpg"
      },
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 4021,
        "width": 6043,
        "id": "previous-events-speakers-bta-global-978-jpg",
        "title": "BTA Global-978",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-978.jpg"
      },
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 3941,
        "width": 5923,
        "id": "previous-events-speakers-bta-global-984-jpg",
        "title": "BTA Global-984",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-984.jpg"
      },
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-speakers-bta-global-991-jpg",
        "title": "BTA Global-991",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-991.jpg"
      },
      {
        "alt": "BTA GlobalX Speakers photo",
        "height": 3858,
        "width": 5798,
        "id": "previous-events-speakers-bta-global-1008-jpg",
        "title": "BTA Global-1008",
        "src": "/assets/gallery/previous-events/Speakers/BTA%20Global-1008.jpg"
      }
    ]
  },
  {
    "id": "previous-events-vips-at-our-celebration",
    "title": "VIPs at Our Celebration",
    "images": [
      {
        "alt": "BTA GlobalX VIPs at Our Celebration photo",
        "height": 3016,
        "width": 4528,
        "id": "previous-events-vips-at-our-celebration-bta-global-129-jpg",
        "title": "BTA Global-129",
        "src": "/assets/gallery/previous-events/VIPs%20at%20our%20celebration/BTA%20Global-129.jpg"
      },
      {
        "alt": "BTA GlobalX VIPs at Our Celebration photo",
        "height": 2711,
        "width": 4070,
        "id": "previous-events-vips-at-our-celebration-bta-global-142-jpg",
        "title": "BTA Global-142",
        "src": "/assets/gallery/previous-events/VIPs%20at%20our%20celebration/BTA%20Global-142.jpg"
      },
      {
        "alt": "BTA GlobalX VIPs at Our Celebration photo",
        "height": 2643,
        "width": 3968,
        "id": "previous-events-vips-at-our-celebration-bta-global-146-jpg",
        "title": "BTA Global-146",
        "src": "/assets/gallery/previous-events/VIPs%20at%20our%20celebration/BTA%20Global-146.jpg"
      },
      {
        "alt": "BTA GlobalX VIPs at Our Celebration photo",
        "height": 2926,
        "width": 4393,
        "id": "previous-events-vips-at-our-celebration-bta-global-153-jpg",
        "title": "BTA Global-153",
        "src": "/assets/gallery/previous-events/VIPs%20at%20our%20celebration/BTA%20Global-153.jpg"
      },
      {
        "alt": "BTA GlobalX VIPs at Our Celebration photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-vips-at-our-celebration-bta-global-563-jpg",
        "title": "BTA Global-563",
        "src": "/assets/gallery/previous-events/VIPs%20at%20our%20celebration/BTA%20Global-563.jpg"
      },
      {
        "alt": "BTA GlobalX VIPs at Our Celebration photo",
        "height": 2825,
        "width": 5973,
        "id": "previous-events-vips-at-our-celebration-bta-global-679-jpg",
        "title": "BTA Global-679",
        "src": "/assets/gallery/previous-events/VIPs%20at%20our%20celebration/BTA%20Global-679.jpg"
      }
    ]
  },
  {
    "id": "previous-events-walk-of-excellence",
    "title": "Walk of Excellence",
    "images": [
      {
        "alt": "BTA GlobalX Walk of Excellence photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-walk-of-excellence-bta-global-961-jpg",
        "title": "BTA Global-961",
        "src": "/assets/gallery/previous-events/walk%20of%20excellence/BTA%20Global-961.jpg"
      },
      {
        "alt": "BTA GlobalX Walk of Excellence photo",
        "height": 4024,
        "width": 6048,
        "id": "previous-events-walk-of-excellence-bta-global-968-jpg",
        "title": "BTA Global-968",
        "src": "/assets/gallery/previous-events/walk%20of%20excellence/BTA%20Global-968.jpg"
      },
      {
        "alt": "BTA GlobalX Walk of Excellence photo",
        "height": 3353,
        "width": 5040,
        "id": "previous-events-walk-of-excellence-bta-global-1069-jpg",
        "title": "BTA Global-1069",
        "src": "/assets/gallery/previous-events/walk%20of%20excellence/BTA%20Global-1069.jpg"
      }
    ]
  }
];
